name: Update Jenkins Version

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get latest Jenkins version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://updates.jenkins.io/download/war/ | grep -oP 'id="\K2\.[0-9]+' | sort -V | tail -n1)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Check current version
        run: |
          CURRENT_VERSION=$(grep "FROM jenkins/jenkins:" Dockerfile | grep -oP ':\K[0-9]+\.[0-9]+(\.[0-9]+)?')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Update Dockerfile
        if: env.CURRENT_VERSION != env.LATEST_VERSION
        run: |
          sed -i "s/jenkins\/jenkins:.*-jdk17/jenkins\/jenkins:${{ env.LATEST_VERSION }}-jdk17/" Dockerfile

      - name: Create Pull Request
        if: env.CURRENT_VERSION != env.LATEST_VERSION
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore: update Jenkins to version ${{ env.LATEST_VERSION }}"
          title: "chore: update Jenkins to version ${{ env.LATEST_VERSION }}"
          body: |
            This PR updates the Jenkins version from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}.
            
            Changes:
            - Updated FROM jenkins/jenkins:${{ env.CURRENT_VERSION }}-jdk17 to jenkins/jenkins:${{ env.LATEST_VERSION }}-jdk17
            
            This is an automated PR created by the Jenkins version update workflow.
          branch: jenkins-version-update
          delete-branch: true
          signoff: true
          labels: |
            dependencies
            automated pr